### ISSUE TITLE
[JOSS Review] What about automated tests?

### ISSUE THREAD

**Issue by melund** [0todd0000/mwarp1d#2]
The minimal  JOSS requirements testing reads: 

> Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)

I guess you could basically argued that some of the [steps in the documentation](http://www.spm1d.org/mwarp1d/examples.html) full fills this requirement. But there is not really any objective criteria to say if the warping was correct. In other words how can I know the library does the same as the last release. 

I think you could benefit from automated testing. Tests are also a nice if you ever get contributions from others as it helps verify their code. Using something like "Github actions" is very easy to setup,

**Comment by 0todd0000** [comment]
Since the package's main purpose is to support manual (and therefore subjective) registration, the only way to thoroughly automate quantitative testing is to simulate mouse and keyboard actions.  This is certainly possible using Qt's event simulators, but this type of automated testing takes much longer to develop than normal script-based testing. Given the JOSS requirement statement (i.e., that step-by-step documentation is sufficient for publication), we decided to choose the documentation route instead.

Please note:
The documentation link you sent above (["steps in the documentation"](http://www.spm1d.org/mwarp1d/examples.html)) contains only a list of scripting examples.

The step-by-step instructions appear in the [User manual](http://www.spm1d.org/mwarp1d/usermanual.html) section, and for those who don't like to read, in the [Screencasts](http://www.spm1d.org/mwarp1d/quickstart.html) section.

Do you think Qt-based mouse+keyboard automation is necessary for publication?

**Comment by melund** [comment]
No. Please don't do any automated GUI testing. That would be overkill for an application like this. It is the underlying logic that could benefit from unit testing. 

You have plenty of scripting examples in `http://www.spm1d.org/mwarp1d/examples.html`, which could easily be tested. Functions like `mwarp1d.warp_manual`

I agree that JOSS does not require unit testing, and that your documentation is extensive enough comply with the minimum JOSS requirements. So I guess this is not a blocker for the review. 

I do understand that you don't see the benefit of automated testing if you haven't used it in other projects. But for open source projects automated CI testing is often quite essential. They can help ensure that your stuff still works when dependencies change over time. How can you be sure that the program will still load with Python 4 when it has been lying around untouched for three years. 

For example, your `Setup.py` and Conda recipe does not mention all the dependencies that you use. This is guaranteed to break at some point when the default QT in Anaconda changes. I think you would have caught this error if you did automated testing. 

Also,  you should consider creating a conda-forge recipe. It will ensure that the package will continue to work in the future and also give you packages for linux.

**Comment by melund** [comment]
I have created a separate issue for the missing dependencies. So I think we can close this if you promise to give automated tests a try in the future ;-)

**Comment by 0todd0000** [comment]
Thank you for that! I do use unit testing in other projects, I just usually keep the unit testing code separate from the main repository. But I agree it could indeed be advantageous to include the unit testing code, will definitely add it in the future. Thank you! 

I've not used conda-forge before, but will definitely try it out, thanks for that as well!
